name: CD workflow

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
  
jobs:
  desplegar_CD:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Prueba
      run: echo "${{ inputs.version }}"
    


