name: CI workflow

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Clonar repo
      uses: actions/checkout@v3

    - name: Leer la versión del package.json
      id: coger_version
      run: echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
      shell: bash

    - name: Taggear mediante custom action
      id: tag-imagen
      uses: ./.github/actions/  
      with:
        nombre_imagen: 'angular_ab'
        version: "${{ env.version }}"

    - name: Construir imagen
      run: docker build -t ${{ vars.USUARIO_DOCKER }}/angular_ab .



    
    - name: Hacer login en DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.USUARIO_DOCKER }}
        password: ${{ secrets.PASSWORD_DOCKER }}


    - name: Subir imagen al registry
      run: docker push ${{ vars.USUARIO_DOCKER }}/${{steps.tag-imagen.outputs.nombre_completo}}
